name: "CI"

on:
  push:
    branches:
      - master
      - "releases/**"
  pull_request:
    branches:
      - "**"

env:
  NODE_VERSION: 14.4.0

jobs:
  buildAll:
    name: Build via lerna run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build


  buildApp:
    name: Build packages/app only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build:app


  buildAppMac:
    name: Build packages/app only on mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build:app

  buildAllMac:
    name: Build via lerna run on mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build

  buildAppParallel:
    name: Build packages in parallel FAILS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: |
          yarn clean && yarn lerna run build
          yarn clean && yarn lerna run build
          yarn clean && yarn lerna run build
          yarn clean && yarn lerna run build
          yarn clean && yarn lerna run build
