name: "CI"

on:
  push:
    branches:
      - master
      - "releases/**"
  pull_request:
    branches:
      - "**"

env:
  NODE_VERSION: 14.4.0

jobs:
  buildAll:
    name: Build via lerna run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn .cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn--${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build


  buildApp:
    name: Build packages/app only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn .cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn--${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build:app



  buildAppMac:
    name: Build packages/app only on mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn .cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn--${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build:app

  buildAllMac:
    name: Build via lerna run on mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ${{ env.NODE_VERSION }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Restore yarn .cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn--${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --production=false
      - name: Build
        run: yarn build

